version: '3.1'

services:
  web:
    build: .
    ports: 
      - 8090:80
    volumes:
      - ./upload:/var/www/html

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports: 
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9998:8080

